package org.vaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.ProgressBar;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CustomerForm extends VerticalLayout {
	protected Image avatar;
	protected Label name;
	protected ProgressBar completeness;
	protected ComboBox title;
	protected TextField firstName;
	protected TextField lastName;
	protected PopupDateField birthdate;
	protected Label ssnDate;
	protected TextField ssnCode;
	protected TextArea notes;
	protected TextField street1;
	protected TextField street2;
	protected TextField zip;
	protected ComboBox city;
	protected ComboBox country;
	protected TextField phone1country;
	protected TextField phone1nr;
	protected CheckBox isMobile;
	protected TextField phone2country;
	protected TextField phone2nr;
	protected CheckBox isMobile2;
	protected Table projects;
	protected Button addProject;
	protected Button delete;
	protected Button cancelButton;
	protected Button saveButton;

	public CustomerForm() {
		Design.read(this);
	}
}
